# Generated by Django 5.1.6 on 2025-05-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('autre', 'Autre'), ('cuisine', 'Cuisine'), ('vetement', 'Vetement'), ('tissu', 'Tissu'), ('argile', 'Argile'), ('maroquineire', 'Maroquineire'), ('alimentaire', 'Alimentaire'), ('accessoire', 'Accessoire')], default='autre', max_length=50),
        ),
    ]
