# Generated by Django 5.1.6 on 2025-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_nl',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
