# Generated by Django 5.1.6 on 2025-11-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderhistory_orderhistoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistoryitem',
            name='product_thumbnail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
