# Generated by Django 5.1.6 on 2025-11-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orderhistoryitem_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
