# Generated by Django 5.2.8 on 2025-11-25 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orderhistory_user_email_alter_orderhistory_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID de session pour les utilisateurs non connectés', max_length=100, unique=True)),
                ('user_email', models.EmailField(blank=True, help_text="Email de l'utilisateur (connecté ou fourni)", max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_transferred_to_admin', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chats', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Chatbot',
                'verbose_name_plural': 'Conversations Chatbot',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_user', models.BooleanField(default=True, help_text='True = utilisateur, False = bot/admin')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read_by_admin', models.BooleanField(default=False)),
                ('sender_name', models.CharField(blank=True, help_text="Nom de l'expéditeur (pour admin)", max_length=100)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store.chatbotconversation')),
            ],
            options={
                'verbose_name': 'Message Chatbot',
                'verbose_name_plural': 'Messages Chatbot',
                'ordering': ['created_at'],
            },
        ),
    ]
