# Generated by Django 5.1.6 on 2025-12-02 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité à retourner')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderhistoryitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.returnrequest')),
            ],
            options={
                'verbose_name': 'Article de retour',
                'verbose_name_plural': 'Articles de retour',
            },
        ),
    ]
