# Generated by Django 5.1.6 on 2025-03-08 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_shopper_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('adress_1', models.CharField(help_text='Adresse de voirie et numero de rue', max_length=240)),
                ('adress_2', models.CharField(blank=True, help_text='batiment etage ', max_length=240)),
                ('city', models.CharField(max_length=1024)),
                ('zip_code', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
