# Generated by Django 5.1.6 on 2025-04-20 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_shopper_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='adress_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='adress_2',
            new_name='address_2',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
