# Generated by Django 5.2.8 on 2025-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_shippingaddress_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('user_data', models.JSONField(default=dict, help_text="Données de l'utilisateur avant suppression")),
            ],
            options={
                'verbose_name': 'Compte supprimé',
                'verbose_name_plural': 'Comptes supprimés',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
